### ISSUE TITLE
Test failures on a fresh clone of dev

### ISSUE THREAD

**Issue by nblumhardt** [structured-log/structured-log#12]
```
npm install
gulp test
```

Output:

```
  1) FileSink should format events as JSON:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at C:\Development\Open Source\nblumhardt\structured-log\test\file-sink.tests.js:47:7
      at WriteStream.onEnd (C:\Development\Open Source\nblumhardt\structured-log\src\core\structured-log.js:242:9)
      at finishMaybe (_stream_writable.js:484:14)
      at afterWrite (_stream_writable.js:362:3)
      at onwrite (_stream_writable.js:352:7)
      at WritableState.onwrite (_stream_writable.js:105:5)
      at fs.js:1799:5
      at FSReqWrap.strWrapper (fs.js:568:5)

  2) LoggerConfiguration #minimumLevel() should suppress events below minimum level:

      AssertionError: 0 == 1
      + expected - actual

      -0
      +1

      at Context.<anonymous> (C:\Development\Open Source\nblumhardt\structured-log\test\structured-log.tests.js:14:14)

  3) LoggerConfiguration #minimumLevel() should apply in pipeline order:
     TypeError: undefined is not a function
      at Context.<anonymous> (C:\Development\Open Source\nblumhardt\structured-log\test\structured-log.tests.js:37:11)

  4) LoggerConfiguration #writeTo() should report failures:
     TypeError: undefined is not a function
      at Context.<anonymous> (C:\Development\Open Source\nblumhardt\structured-log\test\structured-log.tests.js:64:11)
```

Looking into it now.

**Comment by ashleydavis** [comment]
I've fixed issues with tests in my branch. Is is possible to make a pull request up to a specified revision? That'd allow me to get the fixes through. Otherwise I might have to patch them in manually.

**Comment by nblumhardt** [comment]
Howdy - if we merge #13, the changes should be the same as in your branch and thus merge cleanly for you. Cheers!
