### ISSUE TITLE
Experiencing trouble with upgrading to Node 10 - instanceof breaking on arrow function

### ISSUE THREAD

**Issue by charandas** [structured-log/structured-log#58]
These two assertions: [first](https://github.com/structured-log/structured-log/blob/dev/dist/structured-log.es6.js#L696) and [second](https://github.com/structured-log/structured-log/blob/dev/dist/structured-log.js#L775) are failing for me on Node 10. I am moving from Node 8.9.4.

For me, its failing when using `minLevel` as that uses the same `filter` function internally.

1. With regular offering, the `main` field in package.json
```
  let log =
    structuredLog
      .configure()
      .minLevel(level || 'warning')
```

Result:
```
    TypeError: Argument "predicate" must be a function.

      at LoggerConfiguration._3d6‍.r.LoggerConfiguration.filter (node_modules/structured-log/dist/structured-log.js:779:19)
      at LoggerConfiguration.minLevel (node_modules/structured-log/dist/structured-log.js:746:30)
```

2. With es6 offering
```
  let log = configure()
      .minLevel(level || 'warning')
```

Result:
```
    TypeError: Argument "predicate" must be a function.

      at LoggerConfiguration.filter (node_modules/structured-log/dist/structured-log.es6.js:700:19)
      at LoggerConfiguration.minLevel.Object.assign [as minLevel] (node_modules/structured-log/dist/structured-log.es6.js:667:29)
```

`typeof` works, `instanceof` breaks returning `false` presumably (`typeof` returns `'function'` for arrow-function and `'[Function]'` for the vanilla function, not sure why these differences). Given this [issue](https://github.com/nodejs/node/issues/12894), again not sure if `typeof` is the way to go.

Thoughts?

**Comment by charandas** [comment]
Wonder if [this](https://github.com/nodejs/node/issues/13408) is even remotely related.

**Comment by charandas** [comment]
Also, it seems I don't run into this at all when running with ts-node (so in production).

But my unit-testing instrumentation (which is using `ts-jest`) is not at all liking my internal packages that are using [esm](https://github.com/standard-things/esm). One of these packages uses my logging library (which is a small wrapper around structured-log).

**Comment by charandas** [comment]
I will close this since its happening due to some very particular things in my environment. Sorry for the "spam".
